### ISSUE TITLE
Validate hex colors

### ISSUE THREAD

**Issue by ghost** [solero/nostalgia#2]
It seems like received hex colors are never validated if they truly are hex colors. Not doing so could allow errors to be thrown.

I wrote the following code to validate hex colors, it's up to you guys to implement this, I'm not a Python developer.

```python
from re import search

def is_hex(color):
  return search(r'^#(?:[0-9a-fA-F]{3}){1,2}$', color)
```

**Comment by rsakeys** [comment]
Thanks for bringing this up. We've now pushed a solution for this.
